[package]
name = "notes-renamer"
version = "0.0.1"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.89"
argon2 = "0.5.3"
crossterm = "0.28.1"
dirs = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
rand = "0.8.5"
rpassword = "7.3.1"
serde = "1.0.210"
serde_derive = "1.0.210"
tempfile = "3.13.0"
toml = "0.8.19"
tui = "0.19.0"
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
