name: Determine MSRV

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly (Sunday at midnight)

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install cargo-msrv
      run: cargo install cargo-msrv

    - name: Find MSRV
      run: cargo msrv find --output-format json > msrv.json

    # Upload the MSRV as an artifact
    - name: Upload MSRV
      uses: actions/upload-artifact@v4
      with:
        name: msrv
        path: msrv.json
        if-no-files-found: error
        retention-days: 7
